# Site
title:              Triplex
bio:                'Website of Tristan Ross'
description:        "I’m Triplex, also known as Tristan Ross and formerly called Spaceboy Ross, I’m a high school student from the Pacific Northwest in the United States. I do lots of programming and YouTube, the latter is less frequent due to school. I also go camping with Boy Scouts which is fun even though I’m aging out this year, I hope to continue to be involved. My daily driver operating system is Arch Linux and it’s the first rolling distro I’ve ever used. The top three things everyone needs to know about me are that I love girls who are tomboy a lot, I wear trenchcoats a lot, and I do a lot of programming."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://triplexross.github.io/Moon # Will remove the path as soon as this update is done.

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            TriplexRoss
github-url:         TriplexRoss
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          spaceboyross01
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
steam:              spaceboy_ross
#dribbble:          username
#youtube:           username
youtube-channel:    UCpoDb3KlPk35QDyimhLO8zQ
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
